spring.application.name=media-pipeline
# App Info

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/media_pipeline
spring.datasource.username=pipeline_admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Auto-creates your tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
